### ISSUE TITLE
where is the models

### ISSUE THREAD

**Issue by CJDL967** [renguojing/CGNN#1]

**Comment by CJDL967** [comment]
<img width="335" alt="Snipaste_2024-10-30_14-18-37" src="https://github.com/user-attachments/assets/b1c5fe0f-9306-4af3-96f4-f1141d763a18">
<img width="264" alt="Snipaste_2024-10-30_14-18-57" src="https://github.com/user-attachments/assets/16d54532-c3ec-49f5-bc82-56e40a96f361">
<img width="323" alt="Snipaste_2024-10-30_14-19-23" src="https://github.com/user-attachments/assets/2804b43a-f01a-4b64-8434-ad0796c7df99">

**Comment by renguojing** [comment]
"models" has been added now.
